# version: '3'
version: '3'
services:
  redis-stack:
    image: redis/redis-stack:7.0.6-RC6
    ports:
      - '6379:6379'
      - '8001:8001'
  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"